from enum import Enum

class Command(Enum):
  OPEN_APP = 'OPEN'
  WEATHER_INFO = 'WEATHER'
  NEWS_INFO = 'NEWS'
  SEND_NOTIFICATION = 'NOTIFY'
  SEND_NOTIFICATION_DELAYED = 'NOTIFY_DELAY'
  SAVE_MEM = 'ADD'
  DEL_MEM = 'REMOVE'